environment:
  CODECOV_TOKEN:
    secure: 5SygvlgfTewBB3CTmBxUfQ==
  SNYK_TOKEN:
    secure: IyV3vkSZTlBKOtJfcNFk3ZyRSwSRKZUg4YUulfphVR8FCMj94J7az6yIoqNALOPq
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# cache
cache:
  - node_modules -> package.json # cache node_modules, reset if package.json is modified

# fastfail
matrix:
  fast_finish: true

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Install global modules
  - npm install -g npm@next
  # Output useful info for debugging
  - node --version
  - npm --version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  - npm test

# Don't actually build.
build: off
